[book]
title = "Maker Space Wiki"
authors = ["Maker Space Members"]

language = "en"
multilingual = false

src = "src"

[build]
build-dir = "out"
create-missing = false

[output.html]
fold.enable = true
