---
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  book:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download mdBook
        run: |
          set +x

          version="v0.4.40"

          cd /tmp
          archive="mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz"
          wget "https://github.com/rust-lang/mdBook/releases/download/v0.4.40/${archive}"
          tar xzvf "${archive}"
          sudo mv mdbook /usr/bin

          mdbook --version

      - name: Build
        run: mdbook build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        if: github.ref_name == 'main'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: e532cde53d2aaf233bc8f913f31a325f
          command: pages deploy book --project-name=ms-wiki-test

      - name: TODO print deployment-url
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
