---
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  book:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: mdbook build

      # - name: Publish to Cloudflare Pages
      #   uses: cloudflare/pages-action@v1
      #   if: github.ref_name == 'main'
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: YOUR_ACCOUNT_ID
      #     projectName: YOUR_PROJECT_NAME
      #     directory: book
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
